locations = [
    {
        "location": "paris",
        "mission_name": "Show Stopper",
        "disguises": [
            "Tuxedo",
            "Auction Staff",
            "Chef",
            "CICADA Bodyguard",
            "Helmut Kruger",
            "Palace Staff",
            "Security Guard",
            "Stylist",
            "Sheikh",
            "Tech Crew",
            "Vampire Magician"
        ],
        "weapons": [
            "Firearm",
            "Battle Axe",
            "Cleaver",
            "Fire Axe",
            "Fire Poker",
            "Hatchet",
            "Kitchen Knife",
            "Letter Opener",
            "Saber",
            "Scissors",
            "Screwdriver",
            "Explosive",
            "Poison"
        ]
    },
    {
        "location": "sapienza",
        "mission_name": "World of Tomorrow",
        "disguises": [
            "Italian Suit",
            "Biolab Security",
            "Bodyguard",
            "Bohemian",
            "Butler",
            "Church Staff",
            "Cyclist",
            "Delivery Man",
            "Dr. Oscar Lafayette",
            "Gardener",
            "Green Plumber",
            "Hazmat Suit",
            "Housekeeper",
            "Kitchen Assistant",
            "Lab Technician",
            "Mansion Chef",
            "Mansion Security",
            "Mansion Staff",
            "Plague Doctor",
            "Priest",
            "Private Detective",
            "Red Plumber",
            "Roberto Vargas",
            "Store Clerk",
            "Street Performer",
            "Waiter"
        ],
        "weapons": [
            "Firearm",
            "Amputation Knife",
            "Battle Axe",
            "Circumcision Knife",
            "Combat Knife",
            "Fire Axe",
            "Fire Poker",
            "Folding Knife",
            "Hatchet",
            "Katana",
            "Kitchen Knife",
            "Letter Opener",
            "Old Axe",
            "Saber",
            "Scissors",
            "Screwdriver",
            "Explosion",
            "Poison"
        ]
    },

    {
        "location": "marrakesh",
        "mission_name": "A Gilded Cage",
        "disguises": [
            "Summer Suit",
            "Bodyguard",
            "Cameraman",
            "Consulate Intern",
            "Consulate Janitor",
            "Consulate Security",
            "Food Vendor",
            "Fortune Teller",
            "Handyman",
            "Headmaster",
            "Local Printing Crew",
            "Masseur",
            "Military Officer",
            "Military Soldier",
            "Military Elite Soldier",
            "Prisoner",
            "Shopkeeper",
            "Waiter"
        ],
        "weapons": [
            "Battle Axe",
            "Cleaver",
            "Fire Axe",
            "Folding Knife",
            "Letter Opener",
            "Saber",
            "Scissors",
            "Screwdriver",
            "Explosion",
            "Fire Arm",
            "Poison"
        ]
    },

    {
        "location": "bangkok",
        "mission_name": "Club 27",
        "disguises": [
            "Casual Suit",
            "Abel de Silva",
            "Exterminator",
            "Groundskeeper",
            "Hotel Security",
            "Hotel Staff",
            "Jordan Cross' Bodyguard",
            "Kitchen Staff",
            "Morgan's Bodyguard",
            "Recording Crew",
            "Stalker",
            "Waiter"
        ],
        "weapons": [
            "Firearm",
            "Cleaver",
            "Fire Axe",
            "Hatchet",
            "Katana",
            "Kitchen Knife",
            "Letter Opener",
            "Sapper's Axe",
            "Screwdriver",
            "Explosion",
            "Poison"
        ]
    },

    {
        "location": "colorado",
        "mission_name": "Freedom Fighters",
        "disguises": [
            "Tactical Gear",
            "Explosives Specialist",
            "Hacker",
            "Militia Cook",
            "Militia Elite",
            "Militia Spec Ops",
            "Militia Soldier",
            "Militia Technician",
            "Point Man",
            "Scarecrow"
        ],
        "weapons": [
            "Firearms",
            "Branding Iron",
            "Cleaver",
            "Kitchen Knife",
            "Old Axe",
            "Screwdriver",
            "Explosion",
            "Poison"
        ]
    },

    {
        "location": "hokkaido",
        "mission_name": "Situs Inversus",
        "disguises": [
            "VIP Patient",
            "Baseball Player",
            "Bodyguard",
            "Chef",
            "Chief Surgeon",
            "Doctor",
            "Handyman",
            "Helicopter Pilot",
            "Hospital Director",
            "Morgue Doctor",
            "Motorcyclist",
            "Ninja",
            "Patient",
            "Resort Security",
            "Resort Staff",
            "Surgeon",
            "Yoga Instructor"
        ],
        "weapons": [
            "Firearm"
            "Cleaver",
            "Fire Axe",
            "Fire Poker",
            "Katana",
            "Kitchen Knife",
            "Scalpel",
            "Scissors",
            "Screwdriver",
            "Explosion",
            "Poison"
        ]
    },

    {
        "location": "miami",
        "mission_name": "The Finish Line",
        "disguises": [
            "Florida Fit",
            "Aeon Driver",
            "Aeon Mechanic",
            "Blue Seed Driver",
            "Crashed Driver Kronstadt",
            "Event Security",
            "Event Crew",
            "Florida Man",
            "Food Vendor",
            "Journalist",
            "Kitchen Staff",
            "Kowoon Driver",
            "Kowoon Mechanic",
            "Kronstadt Engineer",
            "Kronstadt Mechanic",
            "Kronstadt Researcher",
            "Kronstadt Security",
            "Mascot",
            "Medic",
            "Moses Lee",
            "Pale Rider",
            "Race Coordinator",
            "Race Marshal",
            "Sheikh",
            "Sotteraneo Mechanic",
            "Street Musician",
            "Ted Mendez",
            "Thwack Driver",
            "Thwack Mechanic",
            "Waiter",
        ],
        "weapons": [
            "Firearm",
            "Amputation Knife",
            "Battle Axe",
            "Cleaver",
            "Fire Axe",
            "Kitchen Knife",
            "Old Axe",
            "Scissors",
            "Screwdriver",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "santa_fortuna",
        "mission_name": "Three-Headed Serpent",
        "weapons": [
            "Firearm",
            "Barber Razor",
            "Battle Axe",
            "Cleaver",
            "Kitchen Knife",
            "Letter Opener",
            "Machete",
            "Sacrifical Knife",
            "Scissors",
            "Screwdriver",
            "Explosive",
            "Poisons",
        ],
        "disguises": [
            "Casual Tourist",
            "Barman",
            "Chef",
            "Coca Field Guard",
            "Coca Field Worker",
            "Construction Worker",
            "Drug Lab Worker",
            "Drummer",
            "Elite Guard",
            "Gardener",
            "Hippie",
            "Hippo Whisperer",
            "Mansion Guard",
            "Mansion Staff",
            "Shaman",
            "Street Soldier",
            "Submarine Crew",
            "Submarine Engineer",
            "Tattooist",
        ]
    },

    {
        "location": "mumbai",
        "mission_name": "Chasing a Ghost",
        "disguises": [
            "Imperial Classic",
            "Barber",
            "Bollywood Bodyguard",
            "Bollywood Crew",
            "Dancer",
            "Elite Thug",
            "Food Vendor",
            "Holy Man",
            "Kashmirian",
            "Laundry Foreman",
            "Laundry Worker",
            "Lead Actor",
            "Local Security",
            "Metal Worker",
            "Painter",
            "Queen's Bodyguard",
            "Queen's Guard",
            "Tailor",
            "Thug",
            "Vanya's Servant",
        ],
        "weapons": [
            "Firearms",
            "Amputation Knife",
            "Barber Razor",
            "Beak Staff",
            "Cleaver",
            "Fire Axe",
            "Folding Knife",
            "Kitchen Knife",
            "Letter Opener",
            "Old Axe",
            "Saber",
            "Scissors",
            "Screwdriver",
            "Explosion",
            "Poision",
        ]
    },

    {
        "location": "wilton_creek",
        "mission_name": "Another Life",
        "disguises": [
            "Suburban Suit",
            "Arkian Robe",
            "BBQ Owner",
            "Cassidy Bodyguard",
            "Construction Worker",
            "Exterminator",
            "Garbage Man",
            "Gardener",
            "Gunther Mueller",
            "James Batty",
            "Janus' Bodyguard",
            "Mailman",
            "Nurse",
            "Plumber",
            "Police Deputy",
            "Politician",
            "Politician's Assistant",
            "Real Estate Broker",
            "Server",
            "Sheriff Masterson",
            "Spencer The Hammer Green",
        ],
        "weapons": [
            "Firearm",
            "Battle Axe",
            "Beak Staff",
            "Crowbar",
            "Fire Axe",
            "Hatchet",
            "Kitchen Knife",
            "Letter Opener",
            "Scissors",
            "Screwdriver",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "isle_of_sgail",
        "mission_name": "The Ark Society",
        "disguises":
        [
            "Tuxedo and Mask",
            "Architect",
            "Ark Member",
            "Blake Nathaniel",
            "Burial Robes",
            "Butler",
            "Castle Staff",
            "Chef",
            "Custodian",
            "Elite Guard",
            "Entertainer",
            "Event Staff",
            "Guard",
            "Initiate",
            "Jebediah Block",
            "Knight's Armour",
            "Master of Ceremonies",
            "Raider",
        ],
        "weapons":
        [
            "Firearm",
            "Branding Iron",
            "Circumcision Knife",
            "Katana",
            "Letter Opener",
            "Sacrificial Knife",
            "Viking Axe",
            "Fire Poker",
            "Saber",
            "Screwdriver",
            "Battle Axe",
            "Burial Dagger",
            "Kitchen Knife",
            "Scalpel",
            "Cleaver",
            "Hatchet",
            "Old Axe",
            "Sapper's Axe",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "new_york",
        "mission_name": "Golden Handshake",
        "disguises": [
            "The New Yorker",
            "Bank Robber",
            "Bank Teller",
            "Fired Banker",
            "High Security Guard",
            "Investment Banker",
            "IT Worker",
            "Janitor",
            "Job Applicant",
            "Security Guard",
        ],
        "weapons": [
            "Firearm",
            "Fire Axe",
            "Hobby Knife",
            "Letter Opener",
            "Scissors",
            "Burial Dagger",
            "Folding Knife",
            "Burial Dagger",
            "Kitchen Knife",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "haven_island",
        "mission_name": "The Last Resort",
        "disguises": [
            "The Tropical Islander",
            "Boat Captain",
            "Bodyguard",
            "Butler",
            "Chef",
            "Doctor",
            "Gas Suit",
            "Life Guard",
            "Masseur",
            "Personal Trainer",
            "Resort Guard",
            "Resort Staff",
            "Snorkel Instructor",
            "Swimwear",
            "Tech Crew",
            "Villa Guard",
            "Villa Staff",
            "Waiter",
        ],
        "weapons": [
            "Firearm",
            "Scalpel",
            "Barber Razor",
            "Cleaver",
            "Scissors",
            "Fire Axe",
            "Jarl's Pirate Saber",
            "Letter Opener",
            "Screwdriver",
            "Machete",
            "Folding Knife",
            "Hatchet",
            "Kitchen Knife",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "dubai",
        "mission_name": "The Top of the World",
        "disguises": [
            "Ashen Suit ",
            "Art Crew",
            "Event Security",
            "Event Staff",
            "Famous Chef",
            "Helicopter Pilot",
            "Ingram's Bodyguard",
            "Kitchen Staff",
            "Maintenance Staff",
            "Penthouse Guard",
            "Penthouse Staff",
            "The Assassin",
        ],
        "weapons": [
            "Cleaver",
            "Fire Axe",
            "Folding Knife",
            "Kitchen Knife",
            "Letter Opener",
            "Model of the Sceptre",
            "Ornate Scimitar",
            "Scissors",
            "Screwdriver",
            "Firearm",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "dartmoor",
        "mission_name": "Death in the Family",
        "disguises": [
            "Classic Cut Long Coat Suit",
            "Bodyguard",
            "Gardener",
            "Lawyer",
            "Mansion Guard",
            "Mansion Staff",
            "Photographer",
            "Private Investigator",
            "Undertaker",
        ],

        "weapons": [
            "Kitchen Knife",
            "Scissors",
            "Folding Knife",
            "Hatchet",
            "Screwdriver",
            "Barber Razor",
            "Garden Fork",
            "Letter Opener",
            "Shears",
            "Unicorn Horn",
            "Cleaver",
            "Fire Poker",
            "Saber",
            "Firearm",
            "Explosion",
            "Poision",
        ]

    },

    {
        "location": "berlin",
        "mission_name": "Apex Predator",
        "disguises":
        [
            "Number Six ",
            "Rave On Suit",
            "Bartender",
            "Biker",
            "Club Crew",
            "Club Security",
            "Dealer",
            "Delivery Guy",
            "DJ",
            "Florida Man",
            "Rolf Hirschmüller",
            "Technician",
        ],
        "weapons": [
            "Battle Axe",
            "Concealable Knife",
            "Garden Fork",
            "Kitchen Knife",
            "Fire Axe",
            "Scrap Sword",
            "Combat Knife",
            "Hobby Knife",
            "Old Axe",
            "Screwdriver",
            "Firearm",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "chingqing",
        "mission_name": "End of an Era",
        "disguises":
        [
            "Neon City Suit ",
            "Block Guard",
            "Dumpling Cook",
            "Facility Analyst",
            "Facility Engineer",
            "Facility Guard",
            "Facility Guard (Masked)",
            "Facility Security",
            "Homeless Person",
            "Perfect Test Subject",
            "Researcher",
            "Street Guard",
            "The Board Member",
        ],
        "weapons":
        [
            "Screwdriver",
            "Cleaver",
            "Fire Axe",
            "Hobby Knife",
            "Letter Opener",
            "Scissors",
            "Garden Fork",
            "Kitchen Knife",
            "Scrap Sword",
            "Firearm",
            "Explosion",
            "Poison",
        ]
    },

    {
        "location": "mendoza",
        "mission_name": "The Farewell",
        "disguises": [
            "Black & White Tuxedo Set",
            "47's Signature Suit with Gloves",
            "Asado Chef",
            "Bodyguard",
            "Chief Winemaker",
            "Corvo Black",
            "Gaucho",
            "Head of Security",
            "Lawyer",
            "Mercenary",
            "Providence Herald",
            "Sommelier",
            "Tactical Wetsuit",
            "Tango Musician",
            "Waiter",
            "Winery Worker",
        ],
        "weapons": [
            "Grape Knife",
            "Hatchet",
            "Jarl's Pirate Saber",
            "Sapper's Axe",
            "Fire Axe",
            "Hobby Knife",
            "Kitchen Knife",
            "Old Axe",
            "Screwdriver",
            "Broadsword",
            "Fire Poker",
            "Garden Fork",
            "Icicle",
            "Machete",
            "Shears",
            "Firearm",
            "Explosion",
            "Poison",
        ]
    }]
